### ISSUE TITLE
Ordered list feature request

### ISSUE THREAD

**Issue by mike-ward** [NoMoreDeps/marksjs#1]
Don't know if this is possible given the # is used for headers but would it be possible to define ordered lists as:

#.
#.
#.

The number syntax is awkward. Either you use `1.` for all your items which looks dumb (IMO) or you number them sequentially which is labor-intensive, especially when inserting/deleting/reordering.

Some variants:

```
#. foo

#) bar

(#) baz
```

**Comment by NoMoreDeps** [comment]
Hi @mike-ward,
I agree, the syntax of the ordered list is awkward, it is used to keep the same as the markdown in order to migrate easily.

I definitely like the generic #. syntax. 
I will add this one in my `today` iteration.

Thank you for the feedback.

**Comment by NoMoreDeps** [comment]
Closed with the pull request #2
